version: "3.9"
services:
  pine-valley:
    build:
      context: ./pine-valley
      dockerfile: Dockerfile
    ports:
      - "8091:5000"
    volumes:
      - ./pine-valley:/code
    environment:
      FLASK_DEBUG: "true" 
  grand-oak:
    build:
      context: ./grand-oak
      dockerfile: Dockerfile
    ports:
      - "8092:5000"
    volumes:
      - ./grand-oak:/code
    environment:
      FLASK_DEBUG: "true" 
  postgres:
    image: postgres:13
    restart: always
    hostname: kong-database
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
  kong-bootstrap:
    image: kong:3.3.1-alpine
    hostname: kong-bootstrap
    container_name: kong-bootstrap
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    command: kong migrations bootstrap
    restart: on-failure
  kong:
    image: kong:3.3.1-alpine
    restart: always
    hostname: kong
    container_name: kong
    depends_on:
      - kong-bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    command: kong start
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
networks:
  default:
    name: kong-net

